- name: restart notes-backend
  ansible.builtin.systemd:
    name: notes-backend
    daemon_reload: true
    state: restarted

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted